import type { Metadata } from 'next';
import { LegalDocumentLayout } from '@/app/components/landing/LegalDocumentLayout';

export const metadata: Metadata = {
  title: 'Terms of Service — admirror',
  description: 'Terms and conditions for using admirror.',
};

const LAST_UPDATED = 'May 22, 2026';
const CONTACT_EMAIL = 'diegolinaresd10@gmail.com';

export default function TermsOfServicePage() {
  return (
    <LegalDocumentLayout title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of admirror at{' '}
        <a href="https://www.admirror.app">admirror.app</a> (&quot;Service&quot;). By creating an
        account or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        admirror helps you create static ad creatives by mirroring reference layouts with your product,
        brand, and copy. Features may include reference uploads, product page scraping, AI prompt
        generation, image generation, editing, and access to a curated ad library.
      </p>
      <p>
        We may modify, suspend, or discontinue any part of the Service at any time. We do not guarantee
        uninterrupted availability or specific output quality.
      </p>

      <h2>2. Eligibility and accounts</h2>
      <p>
        You must be at least 16 years old and able to form a binding contract to use admirror. You are
        responsible for maintaining the security of your account and for all activity under it. Notify us
        promptly at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect unauthorized
        access.
      </p>

      <h2>3. Subscriptions, credits, and billing</h2>
      <p>
        Paid plans and billing are handled through Whop. By subscribing, you also agree to Whop&apos;s
        applicable terms. Fees are charged according to the plan you select. Unless otherwise stated:
      </p>
      <ul>
        <li>Subscriptions renew automatically until canceled</li>
        <li>Free trials and promotional credits are limited and may change or end at our discretion</li>
        <li>Refunds are handled according to Whop&apos;s policies and applicable law</li>
      </ul>
      <p>
        You can manage or cancel your subscription through Whop or by contacting support. Cancellation
        stops future charges but may not refund the current billing period unless required by law.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for unlawful, misleading, or harmful purposes</li>
        <li>Upload content you do not have the right to use (including copyrighted ads or trademarks without permission)</li>
        <li>Generate ads that violate advertising platform policies, consumer protection laws, or third-party rights</li>
        <li>Attempt to reverse engineer, scrape, or overload our systems</li>
        <li>Share account access or resell the Service without authorization</li>
        <li>Circumvent usage limits, credit systems, or free-trial restrictions</li>
      </ul>
      <p>
        We may suspend or terminate access if we reasonably believe you have violated these Terms or pose
        a risk to the Service or other users.
      </p>

      <h2>5. Your content</h2>
      <p>
        You retain ownership of content you upload. You grant admirror a non-exclusive, worldwide license
        to host, process, and transmit your content solely to operate and improve the Service, including
        sending it to AI and infrastructure providers as described in our Privacy Policy.
      </p>
      <p>
        You represent that you have all necessary rights to your content and that its use through
        admirror does not infringe any third party&apos;s rights.
      </p>

      <h2>6. AI-generated output</h2>
      <p>
        Outputs are generated by artificial intelligence and may be inaccurate, incomplete, or unsuitable
        for publication without review. You are solely responsible for reviewing, editing, and approving
        any creative before use in advertising or marketing.
      </p>
      <p>
        We do not guarantee that generated ads will perform in any particular way, comply with platform
        policies, or be free from errors. Do not rely on admirror for legal, medical, or financial advice.
      </p>

      <h2>7. Reference ads and library content</h2>
      <p>
        Reference ads and library items may originate from third parties or public ad libraries. They are
        provided for inspiration and structural reference only. You are responsible for ensuring your
        final creatives comply with applicable laws and do not infringe intellectual property or
        misleading-advertising rules.
      </p>

      <h2>8. Intellectual property</h2>
      <p>
        admirror, its branding, software, and original materials are owned by us or our licensors. These
        Terms do not grant you any rights to our trademarks or proprietary technology except as needed to
        use the Service.
      </p>

      <h2>9. Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
        KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, ADMIRROR AND ITS OPERATORS WILL NOT BE LIABLE FOR ANY
        INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA,
        OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
      </p>
      <p>
        OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE IS LIMITED TO THE GREATER OF (A) THE
        AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE THE CLAIM OR (B) USD $100.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless admirror from claims, damages, and expenses (including
        reasonable legal fees) arising from your content, your use of the Service, or your violation of
        these Terms or applicable law.
      </p>

      <h2>12. Termination</h2>
      <p>
        You may stop using the Service at any time. We may terminate or suspend your access for violation
        of these Terms, non-payment, or operational reasons. Provisions that by nature should survive
        termination (including ownership, disclaimers, and limitations of liability) will survive.
      </p>

      <h2>13. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. We will post the updated version on this page and
        update the &quot;Last updated&quot; date. Material changes may also be communicated by email or
        in-app notice. Continued use after changes constitutes acceptance.
      </p>

      <h2>14. Governing law</h2>
      <p>
        These Terms are governed by the laws applicable in the jurisdiction where admirror is operated,
        without regard to conflict-of-law principles. Disputes will be resolved in the courts of that
        jurisdiction, unless mandatory consumer protection laws in your country require otherwise.
      </p>

      <h2>15. Contact</h2>
      <p>
        Questions about these Terms? Email{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalDocumentLayout>
  );
}
