import { metaPageNameForBrand } from './page-name-corrections';
import type { StaticAdSeed } from './types';

/**
 * DTC / Meta Ad Library page names (US). Each name gets company + brand_keyword seeds.
 * Verify with scripts/validate-seed-names.mjs before large ingest.
 */
export const BRANDS_BY_CATEGORY: Record<string, readonly string[]> = {
  sleep: [
    'Casper',
    'Purple',
    'Brooklinen',
    'Boll and Branch',
    'Eight Sleep',
    'Parachute Home',
    'Cozy Earth',
    'Buffy',
    'Saatva',
    'Nectar Sleep',
    'Helix Sleep',
    'Layla Sleep',
    'Tuft and Needle',
    'Bear Mattress',
    'Avocado Green Mattress',
    'DreamCloud',
    'WinkBed',
    'Silk and Snow',
    'Bed Threads',
    'Birch Living',
  ],
  beauty: [
    'Glossier',
    'Drunk Elephant',
    'Tatcha',
    'Summer Fridays',
    'Rare Beauty',
    'Saie',
    'Kosas',
    'Charlotte Tilbury',
    'Tower 28',
    'Topicals',
    'Dieux',
    'Merit',
    'Jones Road Beauty',
    'ILIA Beauty',
    'Glow Recipe',
    "Paula's Choice",
    'The Ordinary',
    'Fenty Beauty',
    'e.l.f. Cosmetics',
    'Olaplex',
    'Anastasia Beverly Hills',
    'Huda Beauty',
    'Kylie Cosmetics',
    'Morphe',
    'ColourPop',
  ],
  supplements: [
    'Omni Creatine',
    'AG1',
    'Athletic Greens',
    'Ritual',
    'Seed',
    'Huel',
    'Bloom Nutrition',
    'Olly',
    'Grüns',
    'Lemme',
    'Transparent Labs',
    'Gorilla Mind',
    'Arrae',
    'MaryRuth Organics',
    'LMNT',
    'Naked Nutrition',
    'Legion',
    'Vital Proteins',
    'Thorne',
    'Onnit',
    'GHOST',
    'Alani Nu',
    'Ryse Supplements',
    'Beam',
    'MUDWTR',
    'Everyday Dose',
    'Cellucor',
  ],
  fitness: [
    'Gymshark',
    'Outdoor Voices',
    'Alo Yoga',
    'Lululemon',
    'Whoop',
    'Fabletics',
    'Vuori',
    'Rhone',
    'Ten Thousand',
    'Nobull',
    'Gymreapers',
    'YoungLA',
    'Alphalete',
    'Set Active',
    'P.volve',
    'Tracksmith',
    'Under Armour',
    'Nike',
    'Adidas',
  ],
  home: [
    'Caraway',
    'Our Place',
    'Branch Basics',
    'Dyson',
    'Shark',
    'Le Creuset',
    'Fellow',
    'BrüMate',
    'YETI',
    'Simplehuman',
    'Blueland',
    'Force of Nature',
    'Ruggable',
    'Burrow',
    'Floyd',
    'Article',
    'Maiden Home',
    'Interior Define',
    'Grove Co',
    'Staub',
  ],
  pet: [
    "The Farmer's Dog",
    'Ollie',
    'Wild One',
    'Fi',
    'BarkBox',
    'Spot and Tango',
    'Sundays for Dogs',
    'Jinx',
    'Native Pet',
    'Open Farm',
    'Pet Honesty',
    'PrettyLitter',
    'Cat Person',
    'Smalls',
    'Chewy',
    'Wild Earth',
    'Ollie Pets',
    'Maev',
    'We Feed Raw',
    'Nom Nom',
  ],
  food: [
    'Magic Spoon',
    'Liquid Death',
    'Olipop',
    'Chomps',
    'Daily Harvest',
    'Athletic Brewing',
    'Poppi',
    'Recess',
    'Cure Hydration',
    'Ghia',
    'De Soi',
    'Mid-Day Squares',
    'Hu Kitchen',
    'Siete Foods',
    'Birch Benders',
    'MUSH',
    'Partake Foods',
    'Daring Foods',
    'Wildgrain',
    'Soylent',
  ],
  apparel: [
    'Allbirds',
    'Bombas',
    "Rothy's",
    'Everlane',
    'Skims',
    'Quince',
    'Cuyana',
    'Reformation',
    'Madhappy',
    'Aritzia',
    'Princess Polly',
    'Fashion Nova',
    'Savage X Fenty',
    'ThirdLove',
    'Victoria Beckham',
    'MeUndies',
    'Parade',
    'Girlfriend Collective',
    'Abercrombie and Fitch',
  ],
  wellness: [
    'Native',
    "Harry's",
    'Function of Beauty',
    'Thinx',
    'Hims',
    'Nutrafol',
    'Dollar Shave Club',
    'Billie',
    'Athena Club',
    'Lume Deodorant',
    'Quip',
    'Cocofloss',
    'Curology',
    'Prose',
    'Keeps',
    'Roman',
    'Ro',
    'Hers',
    'Therabody',
  ],
  tech: [
    'Loop Earplugs',
    'Flare Audio',
    'Eargasm',
    'Happy Ears',
    'Anker',
    'Casetify',
    'Belkin',
    'Oura',
    'Ember',
    'LARQ',
    'Theragun',
    'Hyperice',
    'Backbone',
    'Keychron',
    'Peak Design',
    'Nomad Goods',
    'Mous',
    'PopSockets',
    'BioLite',
  ],
};

export function buildBrandSeeds(): StaticAdSeed[] {
  const out: StaticAdSeed[] = [];
  const globalSeen = new Set<string>();
  for (const [category, names] of Object.entries(BRANDS_BY_CATEGORY)) {
    for (const name of names) {
      const v = name.trim();
      const key = v.toLowerCase();
      if (!v || globalSeen.has(key)) continue;
      globalSeen.add(key);
      const metaPage = metaPageNameForBrand(v);
      out.push({
        seed_type: 'company',
        value: metaPage,
        category,
        brand_keyword: false,
        canonical_label: v,
      });
      out.push({
        seed_type: 'keyword',
        value: v,
        category,
        brand_keyword: true,
        canonical_label: v,
      });
    }
  }
  return out;
}
